# Generated by Django 3.2 on 2021-04-18 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 17, 19, 524902, tzinfo=utc)),
        ),
    ]
