# Generated by Django 3.2 on 2021-04-18 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 57, 40, 539124, tzinfo=utc)),
        ),
    ]
